### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by takluyver** [jupyter/sphinxcontrib_github_alt#1]
This is primarily an internal package for our own use: the code is already in the IPython repo, but we want to use it in other repos, and releasing it as a separate package seems better than duplicating it.

It's `_alt` because there's already [sphinxcontrib-github](https://pypi.python.org/pypi/sphinxcontrib-github/), which works a bit differently. It's easier to package our version than to change all our docs.

The module is not `sphinxcontrib.github_alt` (like most sphinxcontrib packages) because I want to avoid namespace packages - debugging the issues with the `backports` namespace package is no fun.

Does anyone see anything wrong before I put a release up on PyPI?

**Comment by blink1073** [comment]
Update license in the source file perhaps?

**Comment by SylvainCorlay** [comment]
Would this make sense to include this extension in `jupyter-sphinx`?

(an argument *against* it would be that jupyter-sphinx might move to a widgets org after ipywidgets 6.0 when we split.)

**Comment by willingc** [comment]
I would leave it as a standalone for now. Cal Poly has been doing some preliminary work on themes cc/ @ellisonbg 

Was there a particular use case that prompted this? Backporting on notebooks? Bot?

**Comment by ellisonbg** [comment]
Yeah, I wouldn't do further work on the jupyter sphinx theme, the students are most of the way through creating a really nice jupyter theme for sphinx that integrates with the jupyter website cleanly...

**Comment by SylvainCorlay** [comment]
`jupyter-sphinx` is the jupyter extension that render jupyter interactive widgets. Not the theme.

**Comment by takluyver** [comment]
The thing that prompted making a separate package for this was duplicating
it to use in the notebook docs when I was making the 5.0 release notes. I
hope it will be minimal maintenance once it's released.

**Comment by willingc** [comment]
Ah... thanks @SylvainCorlay and @takluyver for the clarifications. Cool use for the release notes.
